### ISSUE TITLE
mwcache로 이름 변경

### ISSUE THREAD

**Issue by lens0021** [femiwiki/caddy-mwcache#1]
wm는 위키미디어의 줄임말로 주로 위키미디어 재단과 그 사이트들(위키백과 등)에 관련된 경우에 자주 쓰는 접두사입니다. 아닌 경우는 지금 생각나는 건 [wvui](https://github.com/wikimedia/wvui) 정도...?
이 모듈처럼 미디어위키와 관련된 경우는 mw를 쓰는 게 더 적절해보이는데 어떨까요?

* Wikimedia에서 wm 검색 결과: https://github.com/wikimedia/?q=wm
* Wikimedia에서 mw 검색 결과: https://github.com/wikimedia/?q=mw

@simnalamburt

**Comment by simnalamburt** [comment]
동의합니다
